language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: false
node_js:
  - '7'
services:
  - mongodb
addons:
  apt:
    sources:
    - mongodb-3.0-precise
    packages:
    - mongodb-org-server
before_script:
  - npm prune
after_success:
  - npm run semantic-release
script:
  - npm run build
  - npm run cover
  - npm run check-coverage
after_success:
  - npm run report-coverage
  - npm run semantic-release
